### ISSUE TITLE
需要更详细的文档，自建peermap和用你的都没有成功

### ISSUE THREAD

**Issue by ctaoist** [sigcn/pg#15]
如果用你的peermap，github授权后就提示 `odic: email is required` 然后就没了。等一会命令行就提示：`Error: request network secret failed: Get "https://synf.in/network/token?state=3bViu5g5ttqBBba2Z": context deadline exceede`

如果我自建peermap，选github授权，浏览器访问授权地址，提示 `provider github not found`

自建pgmap，用生成授权文件的形式，节点可以和pgmap通信，但是两个节点之间ping不通。（一个公网，一个局域网，公网防火墙开启 29877 udp端口）

ps: 我用的nginx反向代理

**Comment by rkonfj** [comment]
> 如果用你的peermap，github授权后就提示 odic: email is required 然后就没了。等一会命令行就提示：Error: request network secret failed: Get "https://synf.in/network/token?state=3bViu5g5ttqBBba2Z": context deadline exceede

使用 github 登录时，要求你的帐号绑定验证过的邮箱。出现这个错误表示你的帐号未绑定邮箱

> 如果我自建peermap，选github授权，浏览器访问授权地址，提示 provider github not found

在`config.yml`中配置 github 的 oauth 信息：
```
oidc_providers:
- name: github
  auth_url: https://github.com/login/oauth/authorize
  token_url: https://github.com/login/oauth/access_token
  user_info_url: https://api.github.com/user
  client_id: ___________1__________
  client_secret: _______2______________
  redirect: https://____3____/oidc/authorize/github
  scopes: ["read:user", "user:email"]
```
github 创建一个 APP,拿到 client_id 和 client_secret 填 [1] [2] ( https://github.com/settings/developers )
你的服务器地址填到 [3]

> 自建pgmap，用生成授权文件的形式，节点可以和pgmap通信，但是两个节点之间ping不通。（一个公网，一个局域网，公网防火墙开启 29877 udp端口）

`pgcli` 加上 `-V -4` 输出更详细的日志，贴上来便于诊断问题
